# Generated by Django 3.0 on 2021-12-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tt_savings',
            name='order_dsp',
        ),
    ]
