# Generated by Django 3.0 on 2022-01-03 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_remove_tt_savings_order_dsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt_deposit',
            name='insert_yyyymm',
            field=models.CharField(default=django.utils.timezone.now, max_length=7, verbose_name='登録年月'),
            preserve_default=False,
        ),
    ]
